### ISSUE TITLE
The label of the Medetec dataset is missing

### ISSUE THREAD

**Issue by zhuhongtao666** [uwm-bigdata/wound-segmentation#1]
The label of the Medetec dataset is missing. Can you provide your annotated label ？

**Comment by tuvovan** [comment]
any updates?

**Comment by uwm-bigdata** [comment]
@zhuhongtao666 @tuvovan the annotations for the Medetec dataset are in wound-segmentation/data/Medetec_foot_ulcer_224/train/labels/ and wound-segmentation/data/Medetec_foot_ulcer_224/test/labels/
