### ISSUE TITLE
The label of meditec is all black

### ISSUE THREAD

**Issue by tuvovan** [uwm-bigdata/wound-segmentation#2]
Hi, 

thank you for the dataset. I just have one concern about the label of meditec part.

I found that they are all black.
![Screen Shot 2021-03-12 at 10 41 27 AM](https://user-images.githubusercontent.com/32134751/110879057-ab886680-831f-11eb-9f92-d3015479e7a6.png)

Could you please share the link to the original one?

thank you!

**Comment by uwm-bigdata** [comment]
> Hi,
> 
> thank you for the dataset. I just have one concern about the label of meditec part.
> 
> I found that they are all black.
> ![Screen Shot 2021-03-12 at 10 41 27 AM](https://user-images.githubusercontent.com/32134751/110879057-ab886680-831f-11eb-9f92-d3015479e7a6.png)
> 
> Could you please share the link to the original one?
> 
> thank you!

Hi, the original Medetec dataset contains only images, and these labels are created by us. They are 8-bit grayscale images with pixel values of 0's and 1's (0 for background and 1 for wound area).

**Comment by tuvovan** [comment]
Ah, so that is why the images are all blacked. We will be able to see the label if we multiply the label image by 255, right?

**Comment by uwm-bigdata** [comment]
> Ah, so that is why the images are all blacked. We will be able to see the label if we multiply the label image by 255, right?

Right, it is easier to feed the 0's and 1's into your model without any manipulation : )

**Comment by tuvovan** [comment]
yeah thank you 👍🏿
