### ISSUE TITLE
FUSEG challenge

### ISSUE THREAD

**Issue by mlyg** [uwm-bigdata/wound-segmentation#6]
Just to check with the submission deadline, when I checked this page last time it was 1st August, but now I see it was brought forwards back to 15th July? 

I have developed a model but I have not prepared the submission yet. Could I please double check when the deadline is?

**Comment by Pele324** [comment]
> Just to check with the submission deadline, when I checked this page last time it was 1st August, but now I see it was brought forwards back to 15th July?
> 
> I have developed a model but I have not prepared the submission yet. Could I please double check when the deadline is?

Hi @mlyg, the deadline is July 15... We changed it from Aug 1 to July 15 following the suggestions from MICCAI. Now we are preparing a report for MICCAI 2021 and late submissions will probably not be in it. But we are open to submissions after the deadline and the leaderboard will be continuously updated.

**Comment by shahzad-ali** [comment]
> But we are open to submissions after the deadline and the leaderboard will be continuously updated.

Can we just submit the predicted binary labels (with the filenames same as the test images) for the evaluation?

**Comment by uwm-bigdata** [comment]
> Can we just submit the predicted binary labels (with the filenames same as the test images) for the evaluation?

We need a runnable docker container :sweat_smile:  In this way we can make predictions and evaluate each submission in exactly the same hardware/software environment.

**Comment by shahzad-ali** [comment]
I am getting the dice score around 0.90 for the validation fold from U-Net like architecture (using the whole images). Believing that there's still room for improvements, I would like to collaborate with you. Let me know your thoughts.

**Comment by Pele324** [comment]
> I am getting the dice score around 0.90 for the validation fold from U-Net like architecture (using the whole images). Believing that there's still room for improvements, I would like to collaborate with you. Let me know your thoughts.

Sure! Please contact me at chuanbo@uwm.edu
